name: Rotina de Backup do PostgreSQL

on:
  schedule:
    - cron: '50 14 * * *'  # Rodará às 11:50 no horário de Brasília

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v2

      - name: Instalar Dependências (PostgreSQL Client 17 e gsutil)
        run: |
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install -y postgresql-client-17
          sudo apt-get install -y google-cloud-cli
        
      - name: Configurar Credenciais do Google Cloud
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        run: |
          echo '${{ secrets.GCS_SERVICE_ACCOUNT_KEY }}' > gcloud-key.json
          gcloud auth activate-service-account --key-file=gcloud-key.json
          gcloud config set project $GCP_PROJECT_ID

      - name: Realizar o Backup e Enviar para o GCS
        env:
          PGPASSWORD: ${{ secrets.DB_PASSWORD }}
          PGUSER: ${{ secrets.DB_USER }}
          PGHOST: ${{ secrets.DB_HOST }}
          PGPORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
        run: |
          BACKUP_FILE="backup_$(date +%Y-%m-%d_%H-%M-%S).sql.gz"
          
          # pg_dump agora usa a versão 17
          pg_dump --host="$PGHOST" --port="$PGPORT" --username="$PGUSER" --dbname="$DB_NAME" --clean --no-owner | gzip > $BACKUP_FILE
          
          gsutil cp "$BACKUP_FILE" "gs://$GCS_BUCKET/backups/$BACKUP_FILE"
          
          echo "Backup concluído e enviado para o Google Cloud Storage!"
